import Head from "next/head";
// import Image from "next/image";
import { Inter } from "next/font/google";
import { Flex, chakra, Image, Heading, Input } from "@chakra-ui/react";

import image from "../../public/assets/landingImage.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Flex flexDir={"column"}>
          <Heading>What Movie?</Heading>
          <Input backgroundColor="whiteAlpha.300" />
        </Flex>
      </MainContainer>
    </>
  );
}

const MainContainer = chakra(Flex, {
  baseStyle: {
    // width: "100%",
    height: "100vh",
    border: "1px solid black",
    backgroundImage: image.src,
    backgroundSize: "cover",
    backgroundPositionX: { base: -400, xl: -200 },
  },
});
