import Head from "next/head";
// import Image from "next/image";
import { Inter } from "next/font/google";
import { Flex, chakra, Heading, Input } from "@chakra-ui/react";
import { BsSearch } from "react-icons/bs";

import image from "../../public/assets/landingImage.jpg";
import { useState } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const [searchQuery, setSearchQuery] = useState("");

  const router = useRouter();

  const onSubmit = (e: any) => {
    console.log(typeof e);
    e.preventDefault();
    router.push(`/search/${searchQuery}`);
  };

  return (
    <>
      <Head>
        <title>Movie Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./assets/siteIcon.png" />
      </Head>
      <MainContainer>
        <ContentContainer>
          <Heading color="whiteAlpha.800" size="2xl">
            What Movie?
          </Heading>
          <form onSubmit={onSubmit}>
            <SearchbarContainer>
              <Input
                variant="unstyled"
                value={searchQuery}
                onChange={(v) => setSearchQuery(v.target.value)}
              />
              <BsSearch
                size={40}
                style={{ marginInline: 10, padding: 5, cursor: "pointer" }}
                onClick={onSubmit}
              />
            </SearchbarContainer>
          </form>
        </ContentContainer>
      </MainContainer>
    </>
  );
}

const MainContainer = chakra(Flex, {
  baseStyle: {
    height: "100vh",
    backgroundImage: image.src,
    backgroundSize: "cover",
    backgroundPositionX: { base: -400, xl: -200 },
  },
});

const SearchbarContainer = chakra(Flex, {
  baseStyle: {
    backgroundColor: "blackAlpha.500",
    paddingY: "5px",
    paddingLeft: "20px",
    borderRadius: "9999px",
    color: "whiteAlpha.800",
    width: "400px",
  },
});

const ContentContainer = chakra(Flex, {
  baseStyle: {
    flexDir: "column",
    rowGap: "25px",
    alignItems: "center",
    position: "absolute",
    right: "10%",
    top: "40%",
  },
});
